-- HRMS Oracle schema

CREATE TABLE HUESPED (
  ID_HUESPED NUMBER PRIMARY KEY,
  DNI_PASAPORTE VARCHAR2(20) NOT NULL UNIQUE,
  NOMBRES VARCHAR2(80) NOT NULL,
  APELLIDOS VARCHAR2(80) NOT NULL,
  NACIONALIDAD VARCHAR2(40) NOT NULL,
  TELEFONO VARCHAR2(20) NOT NULL,
  CORREO VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE HABITACION (
  ID_HABITACION NUMBER PRIMARY KEY,
  NUMERO_HABITACION VARCHAR2(10) NOT NULL UNIQUE,
  TIPO VARCHAR2(30) NOT NULL,
  PRECIO_NOCHE NUMBER(10,2) NOT NULL,
  CAPACIDAD NUMBER(2) NOT NULL,
  ESTADO VARCHAR2(20) NOT NULL,
  CONSTRAINT CK_HABITACION_ESTADO CHECK (ESTADO IN ('Disponible', 'Ocupada', 'Mantenimiento'))
);

CREATE TABLE RESERVA (
  ID_RESERVA NUMBER PRIMARY KEY,
  FECHA_RESERVA DATE NOT NULL,
  FECHA_INGRESO DATE NOT NULL,
  FECHA_SALIDA DATE NOT NULL,
  ESTADO VARCHAR2(20) NOT NULL,
  ID_HUESPED NUMBER NOT NULL,
  ID_HABITACION NUMBER NOT NULL,
  CONSTRAINT CK_RESERVA_ESTADO CHECK (ESTADO IN ('Confirmada', 'Pendiente', 'Cancelada', 'Finalizada')),
  CONSTRAINT CK_RESERVA_FECHAS CHECK (FECHA_SALIDA > FECHA_INGRESO),
  CONSTRAINT FK_RESERVA_HUESPED FOREIGN KEY (ID_HUESPED) REFERENCES HUESPED(ID_HUESPED),
  CONSTRAINT FK_RESERVA_HABITACION FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION(ID_HABITACION)
);

CREATE TABLE FACTURA (
  ID_FACTURA NUMBER PRIMARY KEY,
  NUMERO_FACTURA VARCHAR2(20) NOT NULL UNIQUE,
  FECHA_EMISION DATE NOT NULL,
  MONTO_TOTAL NUMBER(12,2) NOT NULL,
  METODO_PAGO VARCHAR2(20) NOT NULL,
  ID_RESERVA NUMBER NOT NULL,
  CONSTRAINT CK_FACTURA_METODO CHECK (METODO_PAGO IN ('Tarjeta', 'Transferencia', 'Efectivo')),
  CONSTRAINT FK_FACTURA_RESERVA FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA)
);

CREATE TABLE PAGO (
  ID_PAGO NUMBER PRIMARY KEY,
  FECHA_PAGO DATE NOT NULL,
  MONTO NUMBER(12,2) NOT NULL,
  METODO VARCHAR2(20) NOT NULL,
  ID_FACTURA NUMBER NOT NULL,
  CONSTRAINT CK_PAGO_METODO CHECK (METODO IN ('Tarjeta', 'Transferencia', 'Efectivo')),
  CONSTRAINT FK_PAGO_FACTURA FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA)
);

CREATE TABLE EVENTO (
  ID_EVENTO NUMBER PRIMARY KEY,
  CODIGO_EVENTO VARCHAR2(20) NOT NULL UNIQUE,
  NOMBRE VARCHAR2(80) NOT NULL,
  DESCRIPCION VARCHAR2(200),
  FECHA_EVENTO DATE NOT NULL,
  COSTO NUMBER(10,2) NOT NULL
);

CREATE TABLE PARTICIPACION_EVENTO (
  ID_PARTICIPACION NUMBER PRIMARY KEY,
  ID_HUESPED NUMBER NOT NULL,
  ID_EVENTO NUMBER NOT NULL,
  FECHA_INSCRIPCION DATE NOT NULL,
  CONSTRAINT FK_PART_HUESPED FOREIGN KEY (ID_HUESPED) REFERENCES HUESPED(ID_HUESPED),
  CONSTRAINT FK_PART_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO),
  CONSTRAINT UQ_PARTICIPACION UNIQUE (ID_HUESPED, ID_EVENTO)
);

CREATE TABLE EMPLEADO (
  ID_EMPLEADO NUMBER PRIMARY KEY,
  NOMBRES VARCHAR2(80) NOT NULL,
  APELLIDOS VARCHAR2(80) NOT NULL,
  CARGO VARCHAR2(60) NOT NULL,
  CORREO VARCHAR2(100) UNIQUE,
  TELEFONO VARCHAR2(20)
);

CREATE SEQUENCE SEQ_HUESPED START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HABITACION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESERVA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FACTURA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAGO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EVENTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PARTICIPACION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EMPLEADO START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_RESERVA_HUESPED ON RESERVA(ID_HUESPED);
CREATE INDEX IDX_RESERVA_HABITACION ON RESERVA(ID_HABITACION);
CREATE INDEX IDX_FACTURA_RESERVA ON FACTURA(ID_RESERVA);
CREATE INDEX IDX_PAGO_FACTURA ON PAGO(ID_FACTURA);
CREATE INDEX IDX_PART_EVENTO ON PARTICIPACION_EVENTO(ID_EVENTO);
