-- HRMS Oracle schema (modelo con roles)

CREATE TABLE ROL (
  ID_ROL NUMBER(10) PRIMARY KEY,
  NOMBRE VARCHAR2(30) NOT NULL UNIQUE,
  DESCRIPCION VARCHAR2(150)
);

CREATE TABLE USUARIO (
  ID_USUARIO NUMBER(10) PRIMARY KEY,
  ID_ROL NUMBER(10) NOT NULL,
  USERNAME VARCHAR2(30) NOT NULL UNIQUE,
  PASSWORD VARCHAR2(255) NOT NULL,
  ESTADO CHAR(1) DEFAULT 'A' CHECK (ESTADO IN ('A', 'I')),
  FECHA_CREACION DATE DEFAULT SYSDATE,
  CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
);

CREATE TABLE HUESPED (
  ID_HUESPED NUMBER(10) PRIMARY KEY,
  ID_USUARIO NUMBER(10) UNIQUE,
  NOMBRES VARCHAR2(80) NOT NULL,
  APELLIDOS VARCHAR2(80) NOT NULL,
  TIPO_DOCUMENTO VARCHAR2(20),
  NUMERO_DOCUMENTO VARCHAR2(20) UNIQUE,
  TELEFONO VARCHAR2(20),
  CORREO VARCHAR2(100) UNIQUE,
  NACIONALIDAD VARCHAR2(50),
  CONSTRAINT FK_HUESPED_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE HABITACION (
  ID_HABITACION NUMBER(10) PRIMARY KEY,
  NUMERO VARCHAR2(10) UNIQUE NOT NULL,
  TIPO VARCHAR2(30) NOT NULL,
  CAPACIDAD NUMBER(2) NOT NULL,
  PRECIO_NOCHE NUMBER(10,2) NOT NULL,
  ESTADO VARCHAR2(20) DEFAULT 'DISPONIBLE' CHECK (ESTADO IN ('DISPONIBLE', 'OCUPADA', 'MANTENIMIENTO')),
  DESCRIPCION VARCHAR2(300)
);

CREATE TABLE RESERVA (
  ID_RESERVA NUMBER(10) PRIMARY KEY,
  ID_HUESPED NUMBER(10) NOT NULL,
  FECHA_RESERVA DATE DEFAULT SYSDATE,
  FECHA_INGRESO DATE NOT NULL,
  FECHA_SALIDA DATE NOT NULL,
  ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE' CHECK (ESTADO IN ('PENDIENTE', 'CONFIRMADA', 'FINALIZADA', 'CANCELADA')),
  TOTAL NUMBER(10,2),
  CONSTRAINT CK_RESERVA_FECHAS CHECK (FECHA_SALIDA > FECHA_INGRESO),
  CONSTRAINT FK_RESERVA_HUESPED FOREIGN KEY (ID_HUESPED) REFERENCES HUESPED(ID_HUESPED)
);

CREATE TABLE DETALLE_RESERVA (
  ID_DETALLE NUMBER(10) PRIMARY KEY,
  ID_RESERVA NUMBER(10) NOT NULL,
  ID_HABITACION NUMBER(10) NOT NULL,
  PRECIO_NOCHE NUMBER(10,2),
  CANTIDAD_NOCHES NUMBER(3),
  SUBTOTAL NUMBER(10,2),
  CONSTRAINT FK_DETALLE_RESERVA FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA),
  CONSTRAINT FK_DETALLE_HABITACION FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION(ID_HABITACION)
);

CREATE TABLE SERVICIO (
  ID_SERVICIO NUMBER(10) PRIMARY KEY,
  NOMBRE VARCHAR2(80) NOT NULL,
  DESCRIPCION VARCHAR2(300),
  PRECIO NUMBER(10,2) NOT NULL,
  ESTADO CHAR(1) DEFAULT 'A' CHECK (ESTADO IN ('A', 'I'))
);

CREATE TABLE CONSUMO_SERVICIO (
  ID_CONSUMO NUMBER(10) PRIMARY KEY,
  ID_RESERVA NUMBER(10),
  ID_SERVICIO NUMBER(10),
  CANTIDAD NUMBER(5),
  SUBTOTAL NUMBER(10,2),
  FECHA DATE DEFAULT SYSDATE,
  CONSTRAINT FK_CONSUMO_RESERVA FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA),
  CONSTRAINT FK_CONSUMO_SERVICIO FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO)
);

CREATE TABLE EVENTO (
  ID_EVENTO NUMBER(10) PRIMARY KEY,
  NOMBRE VARCHAR2(100),
  DESCRIPCION VARCHAR2(300),
  FECHA_EVENTO DATE,
  COSTO NUMBER(10,2),
  CUPOS NUMBER(5),
  ESTADO CHAR(1) DEFAULT 'A' CHECK (ESTADO IN ('A', 'I'))
);

CREATE TABLE RESERVA_EVENTO (
  ID_RESERVA_EVENTO NUMBER(10) PRIMARY KEY,
  ID_RESERVA NUMBER(10),
  ID_EVENTO NUMBER(10),
  CANTIDAD NUMBER(5),
  SUBTOTAL NUMBER(10,2),
  CONSTRAINT FK_RE_RESERVA FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA),
  CONSTRAINT FK_RE_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
);

CREATE TABLE FACTURA (
  ID_FACTURA NUMBER(10) PRIMARY KEY,
  ID_RESERVA NUMBER(10) UNIQUE,
  FECHA_EMISION DATE DEFAULT SYSDATE,
  SUBTOTAL NUMBER(10,2),
  IGV NUMBER(10,2),
  TOTAL NUMBER(10,2),
  ESTADO_PAGO VARCHAR2(20) DEFAULT 'PENDIENTE' CHECK (ESTADO_PAGO IN ('PENDIENTE', 'PAGADO', 'ANULADO')),
  CONSTRAINT FK_FACTURA_RESERVA FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(ID_RESERVA)
);

CREATE TABLE PAGO (
  ID_PAGO NUMBER(10) PRIMARY KEY,
  ID_FACTURA NUMBER(10),
  FECHA_PAGO DATE DEFAULT SYSDATE,
  METODO_PAGO VARCHAR2(30),
  MONTO NUMBER(10,2),
  CONSTRAINT FK_PAGO_FACTURA FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA)
);

CREATE SEQUENCE SEQ_ROL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HUESPED START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HABITACION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESERVA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DETALLE_RESERVA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SERVICIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONSUMO_SERVICIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EVENTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESERVA_EVENTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FACTURA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAGO START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_USUARIO_ROL ON USUARIO(ID_ROL);
CREATE INDEX IDX_RESERVA_HUESPED ON RESERVA(ID_HUESPED);
CREATE INDEX IDX_DETALLE_RESERVA ON DETALLE_RESERVA(ID_RESERVA);
CREATE INDEX IDX_DETALLE_HABITACION ON DETALLE_RESERVA(ID_HABITACION);
CREATE INDEX IDX_CONSUMO_RESERVA ON CONSUMO_SERVICIO(ID_RESERVA);
CREATE INDEX IDX_CONSUMO_SERVICIO ON CONSUMO_SERVICIO(ID_SERVICIO);
CREATE INDEX IDX_RE_EVENTO ON RESERVA_EVENTO(ID_EVENTO);
CREATE INDEX IDX_RE_RESERVA ON RESERVA_EVENTO(ID_RESERVA);
CREATE INDEX IDX_PAGO_FACTURA ON PAGO(ID_FACTURA);
SELECT * FROM RESERVA 
SELECT * FROM DETALLE_RESERVA 
