-- Seguridad Oracle para HRMS
-- Ejecutar como SYSTEM o SYSDBA, despues de crear el esquema/tablas.
-- Ajustar contrasenas antes de usar en un entorno real.

CREATE USER HRMS_APP IDENTIFIED BY "HrmsApp_2026"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA 100M ON USERS;

CREATE USER HRMS_REPORT IDENTIFIED BY "HrmsReport_2026"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA 20M ON USERS;

CREATE ROLE HRMS_APP_ROLE;
CREATE ROLE HRMS_REPORT_ROLE;

GRANT CREATE SESSION TO HRMS_APP;
GRANT CREATE SESSION TO HRMS_REPORT;

-- Permisos operativos minimos para la aplicacion.
GRANT SELECT, INSERT, UPDATE, DELETE ON ROL TO HRMS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIO TO HRMS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HUESPED TO HRMS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HABITACION TO HRMS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RESERVA TO HRMS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DETALLE_RESERVA TO HRMS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON SERVICIO TO HRMS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONSUMO_SERVICIO TO HRMS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON EVENTO TO HRMS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON RESERVA_EVENTO TO HRMS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FACTURA TO HRMS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON PAGO TO HRMS_APP_ROLE;

GRANT SELECT ON SEQ_ROL TO HRMS_APP_ROLE;
GRANT SELECT ON SEQ_USUARIO TO HRMS_APP_ROLE;
GRANT SELECT ON SEQ_HUESPED TO HRMS_APP_ROLE;
GRANT SELECT ON SEQ_HABITACION TO HRMS_APP_ROLE;
GRANT SELECT ON SEQ_RESERVA TO HRMS_APP_ROLE;
GRANT SELECT ON SEQ_DETALLE_RESERVA TO HRMS_APP_ROLE;
GRANT SELECT ON SEQ_SERVICIO TO HRMS_APP_ROLE;
GRANT SELECT ON SEQ_CONSUMO_SERVICIO TO HRMS_APP_ROLE;
GRANT SELECT ON SEQ_EVENTO TO HRMS_APP_ROLE;
GRANT SELECT ON SEQ_RESERVA_EVENTO TO HRMS_APP_ROLE;
GRANT SELECT ON SEQ_FACTURA TO HRMS_APP_ROLE;
GRANT SELECT ON SEQ_PAGO TO HRMS_APP_ROLE;

-- Permisos solo lectura para reportes/gerencia.
GRANT SELECT ON HUESPED TO HRMS_REPORT_ROLE;
GRANT SELECT ON HABITACION TO HRMS_REPORT_ROLE;
GRANT SELECT ON RESERVA TO HRMS_REPORT_ROLE;
GRANT SELECT ON DETALLE_RESERVA TO HRMS_REPORT_ROLE;
GRANT SELECT ON SERVICIO TO HRMS_REPORT_ROLE;
GRANT SELECT ON CONSUMO_SERVICIO TO HRMS_REPORT_ROLE;
GRANT SELECT ON EVENTO TO HRMS_REPORT_ROLE;
GRANT SELECT ON RESERVA_EVENTO TO HRMS_REPORT_ROLE;
GRANT SELECT ON FACTURA TO HRMS_REPORT_ROLE;
GRANT SELECT ON PAGO TO HRMS_REPORT_ROLE;

GRANT HRMS_APP_ROLE TO HRMS_APP;
GRANT HRMS_REPORT_ROLE TO HRMS_REPORT;

ALTER USER HRMS_APP DEFAULT ROLE HRMS_APP_ROLE;
ALTER USER HRMS_REPORT DEFAULT ROLE HRMS_REPORT_ROLE;

-- Vista de reporte con datos sensibles parcialmente enmascarados.
CREATE OR REPLACE VIEW VW_HUESPED_REPORTE AS
SELECT
  ID_HUESPED,
  NOMBRES,
  APELLIDOS,
  TIPO_DOCUMENTO,
  SUBSTR(NUMERO_DOCUMENTO, 1, 3) || '***' AS DOCUMENTO_MASK,
  SUBSTR(TELEFONO, 1, 3) || '***' AS TELEFONO_MASK,
  CORREO,
  NACIONALIDAD
FROM HUESPED;

GRANT SELECT ON VW_HUESPED_REPORTE TO HRMS_REPORT_ROLE;

-- Consultas de verificacion para capturas.
SELECT GRANTEE, GRANTED_ROLE
FROM DBA_ROLE_PRIVS
WHERE GRANTEE IN ('HRMS_APP', 'HRMS_REPORT')
ORDER BY GRANTEE, GRANTED_ROLE;

SELECT GRANTEE, OWNER, TABLE_NAME, PRIVILEGE
FROM DBA_TAB_PRIVS
WHERE GRANTEE IN ('HRMS_APP_ROLE', 'HRMS_REPORT_ROLE')
ORDER BY GRANTEE, TABLE_NAME, PRIVILEGE;
